# fly.toml app configuration file generated for tear-datingapp on 2023-08-20T15:36:32+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "tear-datingapp"
primary_region = "jnb"

[build]
  image = "tearsorcerer/datingapp:latest"

[env]
  ASPNETCORE_URLS="http://+:8080"
  CloudinarySettings__CloudName="dfjvrsvka"
  CloudinarySettings__ApiKey="312148143311395"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
